### ISSUE TITLE
Warning: Attempt to present <STPopupContainerViewController: 0x7fe9caeabbf0> on <HomeViewController: 0x7fe9cb04f200> whose view is not in the window hierarchy!

### ISSUE THREAD

**Issue by GitCod-Man** [kevin0571/STPopup#91] opened 2017-04-09 05:03 UTC
Warning: Attempt to present <STPopupContainerViewController: 0x7fe9caeabbf0> on <HomeViewController: 0x7fe9cb04f200> whose view is not in the window hierarchy!

**Comment by kevin0571** [comment] 2017-10-11 02:13
Closing this for now since I can't reproduce the issue.

**Closed by kevin0571** 2017-10-11 02:13 UTC
