### ISSUE TITLE
considering in-call status bar frame changes

### ISSUE THREAD

**Issue by hardikdevios** [kevin0571/STPopup#62] opened 2016-04-27 13:05 UTC
**First of all Great Lib and now it will be a part of my default Pods**

All things are great just one thing and it might not be an issue with Lib because i have not explore the lib that much.

# Issue or suggestion
**considering in-call status bar frame changes**

Now i am setting the height of `contentSizeInPopup` in this way and it works awesome with dynamic height

```
override func viewDidLoad() {
        super.viewDidLoad()
        self.tableView.addObserver(self, forKeyPath: "contentSize", options: NSKeyValueObservingOptions.New, context: nil)
        self.contentSizeInPopup = CGSizeMake(UIScreen().bounds.width, self.tableView.contentSize.height ?? 200)

  }

    override func observeValueForKeyPath(keyPath: String?, ofObject object: AnyObject?, change: [String : AnyObject]?, context: UnsafeMutablePointer<Void>) {
        guard let _ = self.tableView else {
            return
        }
        self.contentSizeInPopup = CGSizeMake(UIScreen().bounds.width, self.tableView.contentSize.height ?? 200)

    } 
```
But during the in-call status bar where the size of status bar increased with 40px, At that time popup got shifts down with 20px and was not able to scroll to the bottom of the last cell. so what is the better way to handle this ? any help, Thanks in advanced.

**Comment by kevin0571** [comment] 2016-04-28 03:25
@hardikdevios Thanks!
Actually there is a bug when in-call status bar is showed when popup controller is presented. But in your case, think you can try observing UIApplicationDidChangeStatusBarFrameNotification and get the new frame of status bar before setting new contentSizeInPopup.

**Comment by hardikdevios** [comment] 2016-04-28 15:12
@kevin0571 yes mate i have put that observer and solved issue but thanks for your response. any chance of fixes in the main repo ?

**Comment by kevin0571** [comment] 2016-04-29 02:34
@hardikdevios I will try to fix the in-call status bar issue. PR is welcome.

**Comment by hardikdevios** [comment] 2016-08-01 15:57
Any update on this ?

**Comment by kevin0571** [comment] 2016-08-01 16:38
@hardikdevios I just pushed a fix to master. Let me know if the issue is still there.

**Closed by kevin0571** 2016-08-01 16:38 UTC
Labels: bug

**Comment by hardikdevios** [comment] 2016-08-01 18:12
please add tag and update podspac

**Comment by hardikdevios** [comment] 2016-08-01 18:45
Well issue is fixed cheers buddy. 👍

**Comment by kevin0571** [comment] 2016-08-02 00:48
Cool! Will release a version after I fix another issue. Meanwhile, you could point to HEAD in your Podfile.

Sent from my iPhone

On 2 Aug 2016, at 02:45, Hardik <notifications@github.com<mailto:notifications@github.com>> wrote:


Well issue is fixed cheers buddy. ?

-
