### ISSUE TITLE
navigationBar_titleView_wrongPosition

### ISSUE THREAD

**Issue by nikolay-dementiev** [kevin0571/STPopup#115] opened 2018-04-12 15:22 UTC
I found this issue when upgrade my project to iOS11
the problem looks like an artefact of previous VS's title view in top left corner on destination VS's view when  Push/Unwind segue was called.
..I use custom view on **navigationItem.titleView**

the problem, I think in **- (void)updateNavigationBarAniamted:(BOOL)animated** module: **STPopupController.m** : 
line:
> [_navigationBar addSubview:fromTitleView];

I comment this lines of code for now - but I think it has to be resolved in future
screens with problem:

1. https://github.com/nikolay-dementiev/stPopUpIssue/blob/master/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202018-04-12%20%D0%B2%2017.55.04.png
2. https://github.com/nikolay-dementiev/stPopUpIssue/blob/master/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202018-04-12%20%D0%B2%2017.54.12.png

if I can be helpful - please contact with me

**Comment by kevin0571** [comment] 2018-04-12 22:08
I think this is already fixed in 1.8.3. Did you upgrade your STPopup to latest version?

**Comment by nikolay-dementiev** [comment] 2018-04-13 07:01
Yes, I upgrade my STPopup to latest (1.8.3) version.

**Comment by kevin0571** [comment] 2018-05-03 23:50
@nikolay-dementiev I couldn't reproduce the issue with the example app. Is there any specific steps for reproducing?

**Comment by nikolay-dementiev** [comment] 2018-05-18 08:58
@kevin0571  Hello. I prepare a simple project which reproduce this issue
link on project:  [https://github.com/nikolay-dementiev/stPopUpIssue](url)
what to do: press "Show popUp" button on main **VC**-> press "Next" on **VC1**(/or then press "Back" button on **VC2**)

**Comment by kevin0571** [comment] 2019-03-10 21:06
Fixed in 1.8.4

**Closed by kevin0571** 2019-03-10 21:06 UTC
